name: curie
description: Implementation of the W3C CURIE Syntax 1.0 in Dart.
version: 0.1.0
homepage: https://github.com/namib-project/curie

environment:
  sdk: '>=2.17.0 <3.0.0'

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
